fleetio:
  appsignal: https://push.appsignal.com/1/markers/heroku?name=Fleetio&environment=production&api_key=<%= ENV["APPSIGNAL_API_KEY_PRODUCTION"] %>
fleetio-stage:
  appsignal: https://push.appsignal.com/1/markers/heroku?name=Fleetio&environment=staging&api_key=<%= ENV["APPSIGNAL_API_KEY_STAGING"] %>
